version: '3'

services:
  db:
    image: mysql
    container_name: goDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volume:/var/lib/minesql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    restart: on-failure
    depends_on: 
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    command: redis-server
    container_name: goRedis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10



