services:
  configServer:
    depends_on: 
    - discoveryServer
    build: configserver/
    image: configserver
    ports:
      - "8888:8888"
    environment:
      - GIT_URL=https://github.com/maximums/PAD-config-server
      - GIT_USERNAME=
      - GIT_PASSWORD=
  discoveryServer:
    build: discoveryserver/
    image: discoveryserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  tesetService:
    depends_on:
      - configServer
    build: testservice/
    image: testservice
    environment:
      - CONFIG_HOST=http://discoveryServer:8888/
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  gateway:
    depends_on:
      - discoveryServer
    build: gateway/
    image: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/