version: '3'

services:
  db:
    image: mysql
    container_name: goDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volume:/var/lib/minesql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on: 
      db:
        condition: service_healthy



