services:
  # configServer:
  #   depends_on: 
  #   - discoveryServer
  #   build: configserver/
  #   image: configserver
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - GIT_URL=https://github.com/maximums/PAD-config-server
  #     - GIT_USERNAME=Sdude225
  #     - GIT_PASSWORD=Dest66326rugatorul22
  discoveryServer:
    build: discoveryserver/
    image: discoveryserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  gateway:
    depends_on:
      - discoveryServer
    build: gateway/
    image: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  db:
    image: mysql
    container_name: goDB
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve
    restart: always
    volumes:
      - ./volume:/var/lib/minesql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "users"
    ports:
      - 3306:3306
  

  app:
    build:
      context: securityservice/
      dockerfile: Dockerfile
    container_name: securityService
    ports:
      - 8090:8090
    restart: on-failure
    depends_on: 
      - db
      - redis


  redis:
    image: redis
    command: redis-server
    container_name: goRedis
    ports:
      - 6379:6379




      



  
