services:
  # configServer:
  #   depends_on: 
  #   - discoveryServer
  #   build: configserver/
  #   image: configserver
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - GIT_URL=https://github.com/maximums/PAD-config-server
  #     - GIT_USERNAME=
  #     - GIT_PASSWORD=
  tesetService:
    depends_on:
      - discoveryServer
    build: testservice/
    image: testservice
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  discoveryServer:
    build: discoveryserver/
    image: discoveryserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  gateway:
    depends_on:
      - discoveryServer
    build: gateway/
    image: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=http://discoveryServer:8761/eureka/
  db:
    image: mysql
    container_name: goDB
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve
    restart: always
    volumes:
      - ./volume:/var/lib/minesql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "users"
    ports:
      - 3306:3306
  

  app:
    build:
      context: securityservice/
      dockerfile: Dockerfile
    container_name: securityService
    ports:
      - 8090:8090
    restart: on-failure
    depends_on: 
      - db
      - redis


  redis:
    image: redis
    command: redis-server --requirepass password
    container_name: goRedis
    ports:
      - 6379:6379
  

  session:
    build:
      context: session/
      dockerfile: Dockerfile
    container_name: sessionService
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - session_cache
      - mongodb_container

  session_cache:
    image: redis
    command: redis-server
    container_name: sessionCache
    ports:
      - 8082:6379

  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:



      



  
