spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: teset-service
          uri: lb://teset-service
          predicates:
            - name: Path
              args:
                pattern: "/api/**"
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST}


