spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/**

        - id: security-service
          uri: lb://security-service
          filters:
            - name: CircuitBreaker
              args:
                name: ciotkii_circuitbreaker
                fallbackUri: forward:/welcome
          predicates:
            - name: Path
              args:
                pattern: "/user/**"

        - id: session-service
          uri: lb://session-service
          filters:
            - name: CircuitBreaker
              args:
                name: ciotkii_circuitbreaker
                fallbackUri: forward:/welcome
          predicates:
            - name: Path
              args:
                pattern: "/session/**"

        - id: lobby-service
          uri: lb://lobby-service
          filters:
            - name: CircuitBreaker
              args:
                name: ciotkii_circuitbreaker
                fallbackUri: forward:/welcome
          predicates:
            - name: Path
              args:
                pattern: "/lobby/**"

        - id: testing
          uri: http://httpbin.org
          predicates:
            - Path=/get
          filters:
            - AddResponseHeader=Hello, World

        - id: test_circuitbreaker
          uri: http://httpbin.org
          filters:
            - name: CircuitBreaker
              args:
                name: ciotkii_circuitbreaker
                fallbackUri: forward:/welcome
          predicates:
            - Path=/delay/3

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 2
        slowCallRateThreshold: 5
        slowCallDurationThreshold: 1s
        eventConsumerBufferSize: 10
    metrics:
      enabled: true
    instances:
      ciotkii_circuitbreaker:
        baseConfig: default
        waitDurationInOpenState: 5000
  retry:
    configs:
      default:
        failAfterMaxRetries: true
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
