spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
        default-label: main
  application:
    name: configuration-server
server:
  port: 8888



