spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - name: Path
              args:
                pattern: "/user/**"
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST}


