name: Build and Publish Docker Img

on:
  push:
    branches: [ system ]

jobs:
  check:
    name: Check changed files
    outputs:
      gateway_service: ${{ steps.check_files.outputs.gateway_service }}
      lobby_service: ${{ steps.check_files.outputs.lobby_service }}
      session_service: ${{ steps.check_files.outputs.session_service }}
      payment_service: ${{ steps.check_files.outputs.payment_service }}
      security_service: ${{ steps.check_files.outputs.security_service }}
      test_service: ${{ steps.check_files.outputs.test_service }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
            echo "=============== list modified files ==============="
            git diff --name-only HEAD^ HEAD

            echo "========== check paths of modified files =========="
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == gateway/* ]]; then
                echo "::set-output name=gateway_service::true"
              elif [[ $file == lobby/* ]]; then
                echo "::set-output name=lobby_service::true"
              elif [[ $file == session/* ]]; then
                echo "::set-output name=session_service::true"
              elif [[ $file == paymentservice/* ]]; then
                echo "::set-output name=payment_service::true"
              elif [[ $file == securityservice/* ]]; then
                echo "::set-output name=security_service::true"
              elif [[ $file == testservice/* ]]; then
                echo "::set-output name=test_service::true"
              else
                echo "file does not belong to any service"
              fi
            done < files.txt
  

  lobby_service:
    needs: check
    if: needs.check.outputs.lobby_service == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        context: lobby/
        push: true
        tags: misanea777/distr_game.lobby_service:latest

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        
      